/**
 * @license Apache-2.0
 * Copyright 2026 Truthlocks Inc.
 *
 * Markdown templates for PR comments showing receipt information.
 */

import type {
  ReceiptResponse,
  VerifyReceiptResponse,
  TrustScoreResponse,
} from "../types.js";

/**
 * Hidden HTML marker used to identify and update existing MAIP comments
 * on a PR, preventing duplicate comments on re-runs.
 */
export const COMMENT_MARKER = "<!-- maip-receipt-comment -->";

/**
 * Generate the full PR comment body for a receipt with verification.
 */
export function renderReceiptComment(
  receipt: ReceiptResponse,
  verification: VerifyReceiptResponse | null,
  trustScore: TrustScoreResponse | null,
): string {
  const verificationStatus = verification
    ? verification.valid
      ? "Valid"
      : "Invalid"
    : "Pending";

  const verificationIcon = verification
    ? verification.valid
      ? "\u2705"
      : "\u274C"
    : "\u23F3";

  const trustScoreDisplay = trustScore
    ? `${(trustScore.trust_score * 100).toFixed(1)}%`
    : "N/A";

  const trustIcon = trustScore
    ? trustScore.trust_score >= 0.7
      ? "\u2705"
      : trustScore.trust_score >= 0.4
        ? "\u26A0\uFE0F"
        : "\u274C"
    : "\u2796";

  const warningsSection =
    verification && verification.warnings.length > 0
      ? `\n\n<details>\n<summary>Warnings (${verification.warnings.length})</summary>\n\n${verification.warnings.map((w) => `- ${w}`).join("\n")}\n\n</details>`
      : "";

  const trustSection = trustScore
    ? [
        "",
        "<details>",
        "<summary>Trust Score Components</summary>",
        "",
        "| Component | Score |",
        "|-----------|-------|",
        `| Reputation | ${(trustScore.score_components.reputation * 100).toFixed(1)}% |`,
        `| Key Health | ${(trustScore.score_components.key_health * 100).toFixed(1)}% |`,
        `| Delegation Depth | ${(trustScore.score_components.delegation_depth * 100).toFixed(1)}% |`,
        `| Verification History | ${(trustScore.score_components.verification_history * 100).toFixed(1)}% |`,
        `| Multi-Witness | ${(trustScore.score_components.multi_witness * 100).toFixed(1)}% |`,
        `| Anomaly Penalty | ${(trustScore.score_components.anomaly_penalty * 100).toFixed(1)}% |`,
        "",
        "</details>",
      ].join("\n")
    : "";

  return [
    COMMENT_MARKER,
    "",
    "## MAIP Receipt Summary",
    "",
    "| Field | Value |",
    "|-------|-------|",
    `| Receipt ID | \`${receipt.receipt_id}\` |`,
    `| Chain Hash | \`${receipt.delegation_chain_hash.substring(0, 20)}...\` |`,
    `| Verification | ${verificationStatus} ${verificationIcon} |`,
    `| Trust Score | ${trustScoreDisplay} ${trustIcon} |`,
    `| Agent | \`${receipt.agent_id}\` |`,
    `| Action | \`${receipt.action}\` |`,
    `| Status | ${receipt.status} |`,
    `| Created | ${receipt.created_at} |`,
    warningsSection,
    trustSection,
    "",
    "---",
    "<sub>Generated by [MAIP GitHub Action](https://github.com/truthlocks/maip) - Machine Agent Identity Protocol</sub>",
  ].join("\n");
}

/**
 * Generate a minimal comment body for verification-only mode.
 */
export function renderVerificationComment(
  receiptId: string,
  verification: VerifyReceiptResponse,
): string {
  const icon = verification.valid ? "\u2705" : "\u274C";

  return [
    COMMENT_MARKER,
    "",
    `## MAIP Receipt Verification ${icon}`,
    "",
    "| Field | Value |",
    "|-------|-------|",
    `| Receipt ID | \`${receiptId}\` |`,
    `| Valid | ${verification.valid ? "Yes" : "**No**"} |`,
    `| Verdict | ${verification.verdict} |`,
    `| Details | ${verification.details} |`,
    "",
    verification.warnings.length > 0
      ? `### Warnings\n\n${verification.warnings.map((w) => `- ${w}`).join("\n")}\n`
      : "",
    "---",
    "<sub>Generated by [MAIP GitHub Action](https://github.com/truthlocks/maip) - Machine Agent Identity Protocol</sub>",
  ].join("\n");
}
