/**
 * @license Apache-2.0
 * Copyright 2026 Truthlocks Inc.
 *
 * Create GitHub Check Runs showing receipt chain integrity status.
 */

import * as core from "@actions/core";
import * as github from "@actions/github";
import type { ReceiptResponse, VerifyReceiptResponse } from "../types.js";

const CHECK_NAME = "MAIP Receipt Chain Integrity";

/**
 * Create a GitHub Check Run that reports on the receipt chain integrity.
 * Shows whether the chain of receipts forms a valid, unbroken sequence.
 */
export async function createChainCheck(
  octokit: ReturnType<typeof github.getOctokit>,
  receipt: ReceiptResponse,
  verification: VerifyReceiptResponse,
): Promise<void> {
  const { owner, repo } = github.context.repo;
  const sha = github.context.sha;

  const chainIntact = verification.valid;
  const conclusion = chainIntact ? "success" : "failure";
  const title = chainIntact
    ? "Receipt Chain Intact"
    : "Receipt Chain Integrity Issue Detected";

  const chainDescription = receipt.previous_receipt_id
    ? `This receipt extends an existing chain from receipt \`${receipt.previous_receipt_id}\`.`
    : "This is the **genesis receipt** for this agent in this context - no prior chain exists.";

  const text = [
    "## MAIP Receipt Chain Integrity Report",
    "",
    "### Chain Summary",
    "",
    chainDescription,
    "",
    "| Property | Value |",
    "|----------|-------|",
    `| Current Receipt | \`${receipt.receipt_id}\` |`,
    `| Previous Receipt | ${receipt.previous_receipt_id ? `\`${receipt.previous_receipt_id}\`` : "None (genesis)"} |`,
    `| Chain Hash | \`${receipt.delegation_chain_hash}\` |`,
    `| Attestation | \`${receipt.attestation_id}\` |`,
    `| Chain Valid | ${chainIntact ? "Yes" : "**No**"} |`,
    "",
    "### Verification Details",
    "",
    `- **Verdict**: ${verification.verdict}`,
    `- **Details**: ${verification.details}`,
    "",
    verification.warnings.length > 0
      ? `### Warnings\n\n${verification.warnings.map((w) => `- ${w}`).join("\n")}`
      : "",
    "",
    "### How Receipt Chains Work",
    "",
    "Each MAIP receipt links to its predecessor via the `previous_receipt_id` field,",
    "forming a tamper-evident chain. The `delegation_chain_hash` cryptographically",
    "binds the chain, ensuring any modification to a prior receipt invalidates all",
    "subsequent hashes.",
    "",
    "---",
    "*Generated by [MAIP GitHub Action](https://github.com/truthlocks/maip) - Machine Agent Identity Protocol*",
  ].join("\n");

  const summary = chainIntact
    ? `Chain hash \`${receipt.delegation_chain_hash.substring(0, 16)}...\` verified - integrity intact`
    : `Chain integrity check failed: ${verification.verdict}`;

  try {
    await octokit.rest.checks.create({
      owner,
      repo,
      head_sha: sha,
      name: CHECK_NAME,
      status: "completed",
      conclusion,
      output: {
        title,
        summary,
        text,
      },
    });

    core.info(
      `Created check run '${CHECK_NAME}' with conclusion: ${conclusion}`,
    );
  } catch (error: unknown) {
    core.warning(`Failed to create chain check run: ${String(error)}`);
  }
}
