/**
 * @license Apache-2.0
 * Copyright 2026 Truthlocks Inc.
 *
 * Create GitHub Check Runs showing MAIP receipt verification results.
 */

import * as core from "@actions/core";
import * as github from "@actions/github";
import type { ReceiptResponse, VerifyReceiptResponse } from "../types.js";

const CHECK_NAME = "MAIP Receipt Verification";

/**
 * Create a GitHub Check Run that reports receipt verification status.
 * The check result is visible on the commit and in any open PR.
 */
export async function createReceiptCheck(
  octokit: ReturnType<typeof github.getOctokit>,
  receipt: ReceiptResponse,
  verification: VerifyReceiptResponse,
): Promise<void> {
  const { owner, repo } = github.context.repo;
  const sha = github.context.sha;

  const conclusion = verification.valid ? "success" : "failure";
  const title = verification.valid
    ? "Receipt Verified Successfully"
    : "Receipt Verification Failed";

  const warningsSection =
    verification.warnings.length > 0
      ? `\n\n### Warnings\n\n${verification.warnings.map((w) => `- ${w}`).join("\n")}`
      : "";

  const text = [
    "## MAIP Receipt Verification Report",
    "",
    "| Field | Value |",
    "|-------|-------|",
    `| Receipt ID | \`${receipt.receipt_id}\` |`,
    `| Status | ${receipt.status} |`,
    `| Action | \`${receipt.action}\` |`,
    `| Agent ID | \`${receipt.agent_id}\` |`,
    `| Tenant ID | \`${receipt.tenant_id}\` |`,
    `| Inputs Hash | \`${receipt.inputs_hash}\` |`,
    `| Outputs Hash | \`${receipt.outputs_hash}\` |`,
    `| Chain Hash | \`${receipt.delegation_chain_hash}\` |`,
    `| Attestation ID | \`${receipt.attestation_id}\` |`,
    `| Previous Receipt | ${receipt.previous_receipt_id ? `\`${receipt.previous_receipt_id}\`` : "None (genesis)"} |`,
    `| Created | ${receipt.created_at} |`,
    "",
    "### Verification Result",
    "",
    `- **Valid**: ${verification.valid ? "Yes" : "No"}`,
    `- **Verdict**: ${verification.verdict}`,
    `- **Details**: ${verification.details}`,
    warningsSection,
    "",
    "---",
    "*Generated by [MAIP GitHub Action](https://github.com/truthlocks/maip) - Machine Agent Identity Protocol*",
  ].join("\n");

  const summary = `Receipt \`${receipt.receipt_id}\` - ${verification.valid ? "Verified" : "Verification Failed"} - Chain hash: \`${receipt.delegation_chain_hash.substring(0, 16)}...\``;

  try {
    await octokit.rest.checks.create({
      owner,
      repo,
      head_sha: sha,
      name: CHECK_NAME,
      status: "completed",
      conclusion,
      output: {
        title,
        summary,
        text,
      },
    });

    core.info(
      `Created check run '${CHECK_NAME}' with conclusion: ${conclusion}`,
    );
  } catch (error: unknown) {
    core.warning(`Failed to create check run: ${String(error)}`);
  }
}
