/**
 * @license Apache-2.0
 * Copyright 2026 Truthlocks Inc.
 *
 * Create GitHub Check Runs showing agent trust score details.
 */

import * as core from "@actions/core";
import * as github from "@actions/github";
import type { TrustScoreResponse } from "../types.js";

const CHECK_NAME = "MAIP Trust Score";

/**
 * Map trust score to a check conclusion.
 * >= 0.7 success, >= 0.4 neutral, < 0.4 failure
 */
function scoreToConclusion(score: number): "success" | "neutral" | "failure" {
  if (score >= 0.7) return "success";
  if (score >= 0.4) return "neutral";
  return "failure";
}

/**
 * Render a score bar using Unicode block characters.
 */
function scoreBar(score: number, width: number = 20): string {
  const filled = Math.round(score * width);
  const empty = width - filled;
  return (
    "\u2588".repeat(filled) +
    "\u2591".repeat(empty) +
    ` ${(score * 100).toFixed(1)}%`
  );
}

/**
 * Create a GitHub Check Run showing the trust score for an agent.
 */
export async function createTrustCheck(
  octokit: ReturnType<typeof github.getOctokit>,
  trustScore: TrustScoreResponse,
): Promise<void> {
  const { owner, repo } = github.context.repo;
  const sha = github.context.sha;

  const conclusion = scoreToConclusion(trustScore.trust_score);
  const title = `Trust Score: ${(trustScore.trust_score * 100).toFixed(1)}% (${trustScore.trust_level})`;

  const components = trustScore.score_components;
  const text = [
    "## MAIP Agent Trust Score Report",
    "",
    `**Agent**: \`${trustScore.agent_id}\``,
    `**Trust Level**: ${trustScore.trust_level}`,
    `**Overall Score**: ${scoreBar(trustScore.trust_score)}`,
    `**Trust Ceiling**: ${(trustScore.trust_ceiling * 100).toFixed(1)}%`,
    `**Delegation Depth**: ${trustScore.delegation_depth}`,
    "",
    "### Score Components",
    "",
    "| Component | Score | Bar |",
    "|-----------|-------|-----|",
    `| Reputation | ${(components.reputation * 100).toFixed(1)}% | ${scoreBar(components.reputation, 10)} |`,
    `| Key Health | ${(components.key_health * 100).toFixed(1)}% | ${scoreBar(components.key_health, 10)} |`,
    `| Delegation Depth | ${(components.delegation_depth * 100).toFixed(1)}% | ${scoreBar(components.delegation_depth, 10)} |`,
    `| Verification History | ${(components.verification_history * 100).toFixed(1)}% | ${scoreBar(components.verification_history, 10)} |`,
    `| Multi-Witness | ${(components.multi_witness * 100).toFixed(1)}% | ${scoreBar(components.multi_witness, 10)} |`,
    `| Anomaly Penalty | ${(components.anomaly_penalty * 100).toFixed(1)}% | ${scoreBar(1 - components.anomaly_penalty, 10)} |`,
    "",
    `*Computed at*: ${trustScore.computed_at}`,
    `*Valid until*: ${trustScore.valid_until}`,
    "",
    "---",
    "*Generated by [MAIP GitHub Action](https://github.com/truthlocks/maip) - Machine Agent Identity Protocol*",
  ].join("\n");

  const summary = `Agent \`${trustScore.agent_id}\` trust score: ${(trustScore.trust_score * 100).toFixed(1)}% (${trustScore.trust_level})`;

  try {
    await octokit.rest.checks.create({
      owner,
      repo,
      head_sha: sha,
      name: CHECK_NAME,
      status: "completed",
      conclusion,
      output: {
        title,
        summary,
        text,
      },
    });

    core.info(
      `Created check run '${CHECK_NAME}' with conclusion: ${conclusion}`,
    );
  } catch (error: unknown) {
    core.warning(`Failed to create trust check run: ${String(error)}`);
  }
}
